### ISSUE TITLE
Maybe use Dagger instead of Guice?

### ISSUE THREAD

**Issue by paulschuetz** [ardetrick/amazon-alexa-skill-starter-java#2]
Hey wassup,
wanted to tell you that I really enjoyed this little starter project because it makes it easy to use DI for testing. I recommend checking out dagger, which is also an DI framework from Google which does basically the same as Guice but at compile time rather than runtime (Guice is doing reflection which is slow).
Have a good day!

**Comment by ardetrick** [comment]
Hey!

I'm so happy you enjoyed it. At the time I chose Guice as a learning opportunity but to your point, perhaps something like Dagger or Micronaut would be more relevant, especially for a Lambda use case where the cost of reflection can be quite costly if your container is constantly getting shutdown. 

Hopefully I can get around to it soon, but at the end of the day this was really just a hobby project so who knows :)

Thanks again for the feedback.
